# -*- coding: utf-8 -*-
"""projects

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZTYA6qDH5u4C9TDA1TC4i7KUfLEGaBn

HOUSE PREDICTION :-
using linear and polynomial regression
-->numpy
-->pandas
-->matplotlib
-->scikit learn
"""

# HOUSE PREDICTION :-
# using linear regression
# LIBRARIES:-
# -->numpy
# -->pandas
# -->matplotlib
# -->scikir learn


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (mean_squared_error,root_mean_squared_error,r2_score)

# reading the data from csv file
data = pd.read_csv("house_prices.csv")

# spliting the data into training and testing
x = data.iloc[:,[0]]
y = data.iloc[:,1]

x_train,x_temp,y_train,y_temp = train_test_split(x,y, test_size = 0.5, random_state = 73 )
# we use the val for checking the validation error for knowing the model was underfit or overfit
x_test,x_val,y_test,y_val = train_test_split(x_temp,y_temp, test_size = 0.5, random_state = 23)

# Linear regression
model = LinearRegression()
model.fit(x_train,y_train)

House_price_prediction = model.predict(x_test)
training_prediction = model.predict(x_train)
validation_prediction = model.predict(x_val)

print("predictions of House prices :\n",House_price_prediction)
print("training prediction :\n",training_prediction)
print("validation prediction :\n",validation_prediction)

# we need to check the errors for the predictions was good or not

# mse errors
House_price_prediction_mse = mean_squared_error(y_test,House_price_prediction)
training_prediction_mse = mean_squared_error(y_train,training_prediction)
validation_prediction_mse = mean_squared_error(y_val,validation_prediction)

print("mse of House_price_prediction :\n",House_price_prediction_mse)
print("mse of training_prediction :\n",training_prediction_mse)
print("mse of validation_prediction :\n",validation_prediction_mse)

# error of rmse
House_price_prediction_rmse = root_mean_squared_error(y_test,House_price_prediction)
training_prediction_rmse = root_mean_squared_error(y_train,training_prediction)
validation_prediction_rmse = root_mean_squared_error(y_val,validation_prediction)

print("rmse of House_price_prediction :\n",House_price_prediction_rmse)
print("rmse of training_prediction :\n",training_prediction_rmse)
print("rmse of validation_prediction :\n",validation_prediction_rmse)

House_price_prediction_r2 = r2_score(y_test,House_price_prediction)
training_prediction_r2 = r2_score(y_train,training_prediction)
validation_prediction_r2 = r2_score(y_val,validation_prediction)

print("r2 of House_price_prediction :\n",House_price_prediction_r2)
print("r2 of training_prediction :\n",training_prediction_r2)
print("r2 of validation_prediction :\n",validation_prediction_r2)

# After plotting the data, we observed an approximately
# linear relationship between house size and house price.
# Therefore, we use Linear Regression.

X_line = np.linspace(
    x.min().iloc[0],
    x.max().iloc[0],
    200
).reshape(-1, 1)

y_line = model.predict(X_line)

plt.plot(X_line, y_line, label="Linear Regression")
plt.scatter(x_test, y_test, label="Actual Prices")
plt.scatter(x_test, House_price_prediction, label="Predicted Prices")

plt.xlabel("House Size")
plt.ylabel("House Price")
plt.title("House Price Prediction using Linear Regression")
plt.legend()
plt.show()